"""update_periodicity_enum_to_days

Revision ID: 007ac5b108fa
Revises: 7268b4184d28
Create Date: 2025-11-23 13:17:47.100938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '007ac5b108fa'
down_revision = '7268b4184d28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('periodicity',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('DAILY', 'TWO_DAYS', 'THREE_DAYS', 'WEEKLY', 'BIWEEKLY', 'MONTHLY', name='projectperiodicity'),
               existing_nullable=False,
               existing_server_default=sa.text("'WEEKLY'"))

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index('idx_task_completed_at', ['completed_at'], unique=False)
        batch_op.create_index('idx_task_project_id', ['project_id'], unique=False)
        batch_op.create_index('idx_task_project_status', ['project_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index('idx_task_project_status')
        batch_op.drop_index('idx_task_project_id')
        batch_op.drop_index('idx_task_completed_at')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('periodicity',
               existing_type=sa.Enum('DAILY', 'TWO_DAYS', 'THREE_DAYS', 'WEEKLY', 'BIWEEKLY', 'MONTHLY', name='projectperiodicity'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False,
               existing_server_default=sa.text("'WEEKLY'"))

    # ### end Alembic commands ###
