"""update_periodicity_enum_to_days

Revision ID: 1a23a47554ed
Revises: 007ac5b108fa
Create Date: 2025-11-24 15:48:55.753816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a23a47554ed'
down_revision = '007ac5b108fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('periodicity_days',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text("'WEEKLY'"))
        batch_op.drop_column('periodicity_days_int')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('periodicity_days_int', sa.INTEGER(), server_default=sa.text("'7'"), nullable=False))
        batch_op.alter_column('periodicity_days',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False,
               existing_server_default=sa.text("'WEEKLY'"))

    # ### end Alembic commands ###
