"""add_periodicity_to_project

Revision ID: 4bec88a0a00d
Revises: 00d711bb9302
Create Date: 2025-11-22 20:16:19.031725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bec88a0a00d'
down_revision = '00d711bb9302'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('periodicity', sa.Enum('DAILY', 'WEEKLY', 'BIWEEKLY', 'MONTHLY', 'QUARTERLY', name='projectperiodicity'), nullable=False, server_default='WEEKLY'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('periodicity')

    # ### end Alembic commands ###
